### ISSUE TITLE
Image size does not match

### ISSUE THREAD

**Issue by Ardcy** [srijarkoroy/ArtiStyle#1]
content_img, style_img = ('content.jpg', 'style.jpg')
result = nst_res.run_nst(content_img, style_img)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_3711029/1610500945.py in <module>
      1 content_img, style_img = ('content.jpg', 'style.jpg')
----> 2 result = nst_res.run_nst(content_img, style_img)

~/desktop/ai_safe/ArtiStyle/nst/neural_style_transfer.py in run_nst(self, content_path, style_path)
    217         ''' building the style transfer model '''
    218 
--> 219         model, style_loss, content_loss = self.style_model_and_losses(self.cnn, self.cnn_normalization_mean, self.cnn_normalization_std, content_img, style_img)
    220 
    221         ''' using LBFGS optimizer to run gradient descent on the input image in order to minimise the content and the style losses '''

~/desktop/ai_safe/ArtiStyle/nst/neural_style_transfer.py in style_model_and_losses(self, cnn, cnn_normalization_mean, cnn_normalization_std, content_img, style_img)
    189             ''' adding style loss '''
    190             for name in style_layers:
--> 191                 target_feature = model(style_img).detach()
    192                 styl_loss = StyleLoss(target_feature)
    193                 model.add_module('style_loss_{}'.format(i), styl_loss)

~/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
    117     def forward(self, input):
    118         for module in self:
--> 119             input = module(input)
    120         return input
    121 

~/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/desktop/ai_safe/ArtiStyle/nst/loss_norm.py in forward(self, input)
     36         '''
     37 
---> 38         self.loss = F.mse_loss(input, self.target)
     39         return input
     40 

~/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/nn/functional.py in mse_loss(input, target, size_average, reduce, reduction)
   2926         reduction = _Reduction.legacy_get_string(size_average, reduce)
   2927 
-> 2928     expanded_input, expanded_target = torch.broadcast_tensors(input, target)
   2929     return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
   2930 

~/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/functional.py in broadcast_tensors(*tensors)
     72     if has_torch_function(tensors):
     73         return handle_torch_function(broadcast_tensors, tensors, *tensors)
---> 74     return _VF.broadcast_tensors(tensors)  # type: ignore
     75 
     76 

RuntimeError: The size of tensor a (550) must match the size of tensor b (275) at non-singleton dimension 3

**Comment by sherySSH** [comment]
facing same issue!

**Comment by YoavFekete** [comment]
same issue here

**Comment by niyunsheng** [comment]
I have solved this bug, more details can be seen in the PR. https://github.com/srijarkoroy/ArtiStyle/pull/2

**Comment by niyunsheng** [comment]
The results will be better if the `style_weight=100`

**Comment by srijarkoroy** [comment]
The issue has been resolved, you can run the `test.py` file now providing the path to the content and style image.
